### ISSUE TITLE
REM says "Extension Manager requires Docker!" when running in NAS Docker

### ISSUE THREAD

**Issue by pkmccarthy** [TheAppgineer/roon-extension-manager#16]
Attempting to move Peter's RHEOS to this extension manager as it is his preferred method going forward..

Of course, installing on a synology NAS is a bit different...I have tried several docker run commands (not sure I am mapping the internal directory correctly so I have tried with changes to the -v mapping and without any mapping, it does not appear to be the issue)

I have tried with and without a gid mapping too... here are a few commands

docker run -d \
--network mvlan_network \
--restart unless-stopped \
--name roon-extension-manager \
-v /volume1/docker/roon-extension-manager/data:/home/node/.rem/ \
-v /var/run/docker.sock:/var/run/docker.sock \
-e "TZ=America_Phoenix" \
theappgineer/roon-extension-manager:v1.x-standalone

docker run -d \
--network mvlan_network \
--restart unless-stopped \
--name roon-extension-manager \
--group-add 100 \
-v /volume1/docker/roon-extension-manager/data:/rem \
-v /var/run/docker.sock:/var/run/docker.sock \
-e "TZ=America/Phoenix" \
theappgineer/roon-extension-manager:v1.x-standalone

and a screen shot of the error message:
![image](https://user-images.githubusercontent.com/3913999/207739431-db6fb8bc-e4e1-43c5-a2e2-a965b055db62.png)

attempting to click SETTINGS will crash the ROON app (using the Windows App for testing)

thanks,
Patrick

**Comment by JanKoudijs** [comment]
This error means that the extension cannot communicate with the Docker daemon. This should be taken care of by the `-v /var/run/docker.sock:/var/run/docker.sock` option, make sure there is a file on your NAS named `/var/run/docker.sock` or investigate were else it is located. If you run the command as a normal user (not root) then make sure that the `100` gid is correct.

**Comment by flvinny521** [comment]
I have a similar issue: I install roon-extension-manager using a Docker-Compose file, and it shows up properly in the Extensions menu. I can open the settings and choose an extension to download from the repository. However, immediately upon clicking save, the roon-extension-manager settings window closes, bringing me back to the main Extensions menu, and only then does the "Extension Manager requires Docker" message appear. The extension I chose to install is not installed.

My docker-compose.yml:


```
version: '2.4'
services:
  rem:
    image: theappgineer/roon-extension-manager:v1.x-standalone
    container_name: rem
    group_add:
      - 993
    environment:
      - TZ=America/New_York
    volumes:
      - rem_data:/home/node/.rem/
      - /var/run/docker.sock:/var/run/docker.sock
    network_mode: host
    restart: unless-stopped
volumes:
  rem_data:
```
