### ISSUE TITLE
Extension Manager Requires Docker

### ISSUE THREAD

**Issue by Ryonez** [TheAppgineer/roon-extension-manager#21]
So I'm someone else having the above error.

The current compose file:

```
version: '2.4'
services:
  alteria-rem:
    container_name: alteria-rem
    network_mode: host
    group_add:
      - ${DOCKER_GID}
    environment:
        - TZ=Pacific/Auckland
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - '/mnt/user/appdata/alteria-rem/:/home/node/.rem/:rw'
    image: 'theappgineer/roon-extension-manager:v1.x-standalone'
```

The gui is set to the correct value, and I've confirmed that by going into the container and looking in the file location as well.
Portainer is on this system, and can successfully connect and control docker, it is how I manage docker on this system.
