### ISSUE TITLE
Problem running rem in Docker using Macvlan

### ISSUE THREAD

**Issue by corykim** [TheAppgineer/roon-extension-manager#22]
Hi there, and thanks for such a great project. I'm running rem in docker using Macvlan networking. Here are the relevant parts of my docker-compose:

```
  rem:
    extends:
      file: includes/roon-extension-manager.yml
      service: rem
    networks:
      vlan:
        ipv4_address: 10.0.3.23
  roon:
    extends:
      file: includes/roon.yml
      service: roon
    networks:
      vlan:
        ipv4_address: 10.0.3.20
```

and the include file:

```
version: "3.9"
services:
  rem:
    image: theappgineer/roon-extension-manager:v1.x-standalone
    container_name: rem
    group_add:
      - 998
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/app-data/roon-extension-manager:/home/node/.rem/
    environment:
      TZ: ${time_zone}
```

There are two problems with my install:

1. When I go to REM within Roon, I see an error message: "Extension Manager should run in Docker!"
2. When I try to install an extension, it doesn't install. I see the following error in the docker log:
```
Inf: Installing: BT Entrypoint...
-> CONTINUE 1 Changed {"message":"Installing: BT Entrypoint...","is_error":false}
-> CONTINUE 1 Changed {"message":"Installing: BT Entrypoint...","is_error":false}
-> CONTINUE 1 Changed {"message":"Installing: BT Entrypoint...","is_error":false}
/home/node/docker-lib.js:149
            log_config = info.HostConfig.LogConfig;
                              ^

TypeError: Cannot read property 'HostConfig' of null
    at Object.callback (/home/node/docker-lib.js:149:31)
    at /home/node/node_modules/dockerode/lib/container.js:74:12
    at /home/node/node_modules/docker-modem/lib/modem.js:332:7
    at getCause (/home/node/node_modules/docker-modem/lib/modem.js:354:7)
    at Modem.buildPayload (/home/node/node_modules/docker-modem/lib/modem.js:323:5)
    at IncomingMessage.<anonymous> (/home/node/node_modules/docker-modem/lib/modem.js:295:14)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Can someone help me resolve this?
